### ISSUE TITLE
Handle multiple pull information in one dialog

### ISSUE THREAD

**Issue by kafelix496** [coding-for-fun-org/frontend#158]
### Describe the feature

prerequisite: #153 

1. Create a button to open a dialog for selected pull requests.
2. Add arrow keys `<` and `>` inside the dialog.
    1. If the user clicks `>`, show the next selected pull information.
    2. If the user clicks `<`, show the previous selected pull information.
    3. If there is no previous pull, block the `<` button.
    4. If there is no next pull, block the `>` button.

**Comment by jskurt** [comment]
3. modify footer
   1. `Cancel` is keep.
   2. `Link to Pull Request` to Review.
   3. `Cancel` make 3 radioButtons on the left.
