### ISSUE TITLE
Change icons from @radix-ui/react-icons to lucide-react

### ISSUE THREAD

**Issue by kafelix496** [coding-for-fun-org/frontend#180]
### Describe the feature

react-icons package has so limited icons. Let's change to lucide-react package.
I already installed it so find every `@radix-ui/react-icons` icon and replace the same icon using `lucide-react`.

**Comment by jskurt** [comment]
radix have 2 trash icons, I think trash2Icon is better so I applied, is it okay? :)
<img width="130" alt="image" src="https://github.com/coding-for-fun-org/frontend/assets/97920073/320f166e-2a69-47d7-a01e-47db05ff3f31">
[right is trash2Icon]
