### ISSUE TITLE
use customized elements

### ISSUE THREAD

**Issue by kafelix496** [coding-for-fun-org/frontend#38]
### Describe the feature

1. update the `pull-list-by-repo` and `pull-review-form` components using customized elements
    1.  `src/elements/checkbox/checkbox.tsx`
    2. `src/elements/label/label.tsx`
    3. `src/elements/textarea/textarea.tsx`
    4. `src/elements/button/button.tsx`
    5. `src/elements/collapsible/collapsible.tsx`
    5. `ChevronDownIcon` <- icon
    6.  `ChevronRightIcon` <- icon

**Comment by jskurt** [comment]
Modified
1. PullListByRepo -> pull-list-by-repo
2. PullReviewForm -> pull-review-form
