### ISSUE TITLE
approve button should not be activated if one of pull request is created by himself

### ISSUE THREAD

**Issue by kafelix496** [coding-for-fun-org/frontend#50]
### Describe the bug

approve button should not be activated if one of pull request is created by himself because pull request can't be approved by the creator.

### To reproduce

1. select a pull request that is created by yourself.
2. check whether the approve button is disabled or not.

**Comment by jskurt** [comment]
> ### Describe the bug
> approve button should not be activated if one of pull request is created by himself because pull request can't be approved by the creator.
> 
> ### To reproduce
**What does 'To reproduce' means? 😞**
> 1. select a pull request that is created by yourself.
> 2. check whether the approve button is disabled or not.
